---
- name: Update the apt cache
  apt:
    update_cache: yes

- name: Ensure desktop environment including browser is installed
  apt:
    name:
      - xserver-xorg
      - x11-xserver-utils
      - xinit
      - lightdm
      - openbox
      - curl
      - firefox-esr
    install_recommends: false
    state: present

- name: Make sure lightdm config directory is present
  file:
    path: /etc/lightdm/lightdm.conf.d/
    state: directory

- name: Enable lightdm autologin using the pi user
  copy:
    src: kiosk.conf
    dest: /etc/lightdm/lightdm.conf.d/

- name: Make sure openbox config directory is present
  file:
    path: /home/pi/.config/openbox
    state: directory
    owner: pi
    group: pi

- name: Setup kiosk start script
  template:
    src: kiosk.sh
    dest: /home/pi/kiosk.sh
    owner: pi
    group: pi
    mode: 0755
  notify: restart lightdm

- name: Let openbox call the kiosk.sh start script
  copy:
    src: autostart
    dest: /home/pi/.config/openbox/
    owner: pi
    group: pi
  notify: restart lightdm
